style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/@GH_USER@/@GH_REPO@
options:
  commits:
    filters:
      type:
        - break
        - build
        - doc
        - example
        - feat
        - fix
        - loc
        - misc
        - perf
        - refactor
        - test
  commit_groups:
    title_maps:
      break: ğŸš¨ Breaking Changes
      build: ğŸ“¦ Build
      doc: ğŸ“š Documentation
      example: ğŸ›  Examples
      feat: âœ¨ New Features
      fix: ğŸ› Bug Fixes
      perf: âš¡ï¸ Performance
      refactor: â™»ï¸ Refactors
      test: ğŸš¦ Tests
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
